- server/aboutInfo.js
- server/aboutInfo.test.js
- server/index.js
- src/about.js
- src/logBrowser.js
Implemented features #7 and #8. Works on Ras Pi
> Disk space and shutdown

- python/rtsp-server.py
- server/index.js
- server/videostream.js
- server/videostream.test.js
- src/video.js
Alternative streaming option for QgroundControl. For #22
> Add UDP Video streaming

- deploy/RasPi-ubuntu20-deploy.sh
- package.json
- server/flightController.js
- server/videostream.js
This PR adds support for Ubuntu 20.04.1 LTS running on the Raspberry Pi.
Working:
Network management
Serial port
Not working:
Ras Pi Camera
> Add Ubuntu support

- deploy/jetson.sh
- python/gstcaps.py
- python/rtsp-server.py
- server/flightController.js
- server/index.js
- server/videostream.js
Add support for the Jetson Nano
> Add Jetson support

- package-lock.json
- server/adhocManager.js
- server/adhocmanager.test.js
- server/index.js
- src/AppRouter.js
- src/adhocwifi.js
- src/networkconfig.js
> Network: Add adhoc Wifi mode

- server/index.js
> Server: Fix typo in UDP video IP

- server/index.js
- src/video.js
> Otheripfix

- deploy/RasPi2-3-4-deploy.sh
- package.json
- rpanion.service
- server/aboutInfo.js
- src/about.js
> Better upgrade UI

- deploy/RasPiZero-deploy.sh
- server/index.js
- server/networkManager.js
- src/networkconfig.js
-Now able to view and add scanned Wifi networks
> Improved Wifi

- .github/workflows/node.js.yml
- .gitignore
- README.md
- deploy/RasPi-ubuntu20-deploy.sh
- deploy/RasPi2-3-4-deploy.sh
- deploy/RasPiZero-deploy.sh
- deploy/build.sh
- deploy/jetson-deploy.sh
- package-lock.json
- package.json
- python/wireguardconfig.py
- server/flightController.js
- server/flightController.test.js
- server/index.js
- server/vpn.js
- server/vpn.test.js
- src/AppRouter.js
- src/flightcontroller.js
- src/index.js
- src/vpnconfig.js
> Add VPN service for Zerotier and Wireguard

- deploy/RasPi-ubuntu20-deploy.sh
- deploy/RasPi2-3-4-deploy.sh
- deploy/RasPiZero-deploy.sh
- package-lock.json
- python/rtsp-server.py
- python/tlog2kmz.py
- server/cloudUpload.js
- server/flightLogger.js
- server/flightLogger.test.js
- server/index.js
- server/logConverter.js
- src/AppRouter.js
- src/logBrowser.js
This PR adds a KMZ downloadable file for each .Tlog generated the file by running a script on OS boot.
~~note: That is a WIP, I tested on Ubuntu and found some issues on RPiOS.~~
Edit: passed locally on a RPi & ubuntu.
> Add KMZ as a log file

- README.md
- deploy/RasPi-ubuntu20-deploy.sh
- deploy/RasPi2-3-4-deploy.sh
- deploy/RasPiZero-deploy.sh
- deploy/jetson-deploy.sh
- python/gstcaps.py
- python/rtsp-server.py
- python/tlog2kmz.py
- server/cloudUpload.js
- server/cloudUpload.test.js
- server/flightController.js
- server/index.js
- server/logConverter.js
- src/cloud.js
- src/flightcontroller.js
- src/logBrowser.js
- src/networkconfig.js
Any other fixes for bugs found during testing
> 0.9 Release fixes Pt2

- deploy/RasPi2-3-4-deploy.sh
- deploy/RasPiZero-deploy.sh
- python/gstcaps.py
- python/rtsp-server.py
Add support for Jetson CSI cameras, plus hardware acceleration of H264 compression
> Add Jetson Camera Support

- deploy/upgrade.sh
There was a file rename not reflected here.
> Rename build.sh to build_rpanion.sh

- deploy/RasPi-ubuntu20-deploy.sh
- deploy/RasPi2-3-4-deploy.sh
- deploy/RasPiZero-deploy.sh
- deploy/install_common_libraries.sh
- package.json
- server/index.js
- src/cloud.js
- src/flightcontroller.js
- src/logBrowser.js
- src/video.js
- More consistent UI
- Fix shutdown delay issues
- Don't install picamera2 on Ubuntu20
> More Improvements

- python/wireguardconfig.py
Fix for "Wireguard VPN shows unknown for working connections" in #116
> Network: Better Wireguard status

- .github/workflows/codeql-analysis.yml
- .github/workflows/node.js.yml
- README.md
- deploy/RasPi-ubuntu22-deploy.sh
- deploy/install_common_libraries.sh
- python/gstcaps.py
Works apart from the CSI Camera ... apparently not supported in 22.04 :(
> Add Ubuntu 22.04 Support

- server/networkManager.js
> Network: Allow spaces in ssid

- deploy/x86-ubuntu20-deploy.sh
Change the reference of the bash file that is been use ./build to ./build_rpanion
> Change the reference of the build bash

- server/adhocManager.js
- server/adhocManager.test.js
- server/index.js
- src/adhocwifi.js
> Adhoc improvements

- README.md
- deploy/RasPi-ubuntu20-deploy.sh
- deploy/RasPi-ubuntu22-deploy.sh
- deploy/RasPi2-3-4-deploy.sh
- deploy/jetson-deploy.sh
- deploy/x86-ubuntu20-deploy.sh
> Deploy: Use new nodejs install method

- python/gstcaps.py
- python/rtsp-server.py
Fixed a small bug with not all video options being presented
> Video: Ensure all resolution formats are listed

- server/flightController.js
> FlightController: Fix Ubuntu non detection

- server/vpn.js
> VPN: Better Zerotier online detection

- python/rtsp-server.py
- src/video.js
> Video: Add multicast for RTP

- python/rtsp-server.py
Major refactor of the rtsp server. Non-functional change, but the code's much easier to maintain
> Video: re-work rstp-server (nfc)

- server/networkManager.js
- server/vpn.js
- src/networkconfig.js
Fix a bunch of small issues with the networking page - WIfi settings not always getting saved, etc
> Network fixes

- python/rtsp-server.py
Fix for #250 
For the Rpi <5, ensure the hardware x264 encoder is used for video streaming.
> Video: Use hardware encoding on < Rpi5

- python/gstcaps.py
- python/rtsp-server.py
- server/index.js
- server/videostream.js
- server/videostream.test.js
- src/video.js
For #274 and #275
For CSI, it's tricky to query available resolutions for video, so needs to be hard-set for now
> Add H265 compression option

- server/flightController.js
- server/flightController.test.js
- server/index.js
- src/flightcontroller.jsx
> Flightcontroller: Allow networked input
